### ISSUE TITLE
pattern matching tar

### ISSUE THREAD

**Issue by dirkjanfaber** [wmacevoy/latex-docker#1]
When adding this to an existing latex project, I got the following error:
```
tar: Pattern matching characters used in file names
tar: Use --wildcards to enable pattern matching, or --no-wildcards to suppress this warning
tar: */bin: Not found in archive
tar: Pattern matching characters used in file names
tar: Use --wildcards to enable pattern matching, or --no-wildcards to suppress this warning
tar: */dockers: Not found in archive
tar: Exiting with failure status due to previous errors
```
After adding the suggested `--wildcards` option, tar stopped complaining and extracted the bin and dockers directories as expected: `curl -L https://github.com/wmacevoy/latex-docker/tarball/master | tar zxv --strip=1 --wildcards '*/bin' '*/dockers'`

**Comment by wmacevoy** [comment]
which os are you using?

**Comment by wmacevoy** [comment]
I added this information to the readme.  On OS X --wildcards is not supported, so there is no single simple command to use.  Thanks for the info!

**Comment by dirkjanfaber** [comment]
> which os are you using?

I am using raspbian (linux).
